### ISSUE TITLE
root_delay parsing incoherent with NTP RFC

### ISSUE THREAD

**Issue by josephernest** [Tipoca/ntplib#1]
Here the parsing: https://github.com/Tipoca/ntplib/blob/master/ntplib.py#L185

    self.root_delay = float(unpacked[4])/2**16

seems incoherent with https://tools.ietf.org/html/rfc5905, page 21:

    Root Delay (rootdelay): Total round-trip delay to the reference
      clock, in NTP short format.

and page 12:

       0                   1                   2                   3
       0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |          Seconds              |           Fraction            |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

                               NTP Short Format

Or maybe is it another NTP version used here?

**Comment by xandkar** [comment]
Hi @josephernest, this repository is just a(n irregularly-updated) clone. The actual project home and the author's conact info are listed on the `ntplib`'s PyPI page: https://pypi.org/project/ntplib/

**Comment by programadorhedonista** [comment]
> seems incoherent with https://tools.ietf.org/html/rfc5905, page 21:

Where is the error?

**Comment by hynekcer** [comment]
It is really implemented correctly. The code for all attributes that use "NTP Short Format" is in accordance with the RFC. Output values are also in accordance with other tools from the native NTP software.

It can be verified easily e.g. if a ntp daemon is running on the localhost:

    $ python -c "import ntplib; print(ntplib.NTPClient().request('localhost').root_dispersion)"
    0.019424
    $ ntpq -c rl | grep rootdisp;
    ...  rootdisp=19.430
and you get a similar value in miliseconds (not the exactly same because ntpq reports from more than 32 bits of the root dispersion on localhost) The root delay ia also correct simalrly.
